# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77bfd1f77498eccfe873438ce30b716f5ebace2c1565e9b7141a5e62c1a458ecd3d93ed2e43a5008823f1d6a14e749c92b919c02b3716adf52f5b3110bbc25cb

test:
  secret_key_base: 55edbd5eb0f89ab9f9bb0be315cb8561508a9d2d36f7301e94ff413ead7b88d84e26dfabfe1cbf3e4d0f396c8ad3535faa231ea31a253cff78d89b2b5d184619

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
